'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace Sriletisim
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://posgrup.com/", ConfigurationName:="Sriletisim.WSiletisimSoap")>  _
    Public Interface WSiletisimSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://posgrup.com/ReadDataSet", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ReadDataSet(ByVal Sql As String, ByVal Tbl As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://posgrup.com/ReadDataTable", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ReadDataTable(ByVal Sql As String, ByVal Tbl As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://posgrup.com/ReadDataTableXml", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ReadDataTableXml(ByVal Sql As String, ByVal Tbl As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://posgrup.com/ExecuteSql", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ExecuteSql(ByVal Sql As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://posgrup.com/UploadSatislar", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function UploadSatislar(ByVal Ds As System.Data.DataSet) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://posgrup.com/UploadDataTable", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function UploadDataTable(ByVal Dt As System.Data.DataTable) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://posgrup.com/YesNo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function YesNo(ByVal UserId As String, ByVal SendCode As String, ByVal Reply As Boolean) As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WSiletisimSoapChannel
        Inherits Sriletisim.WSiletisimSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WSiletisimSoapClient
        Inherits System.ServiceModel.ClientBase(Of Sriletisim.WSiletisimSoap)
        Implements Sriletisim.WSiletisimSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ReadDataSet(ByVal Sql As String, ByVal Tbl As String) As System.Data.DataTable Implements Sriletisim.WSiletisimSoap.ReadDataSet
            Return MyBase.Channel.ReadDataSet(Sql, Tbl)
        End Function
        
        Public Function ReadDataTable(ByVal Sql As String, ByVal Tbl As String) As System.Data.DataTable Implements Sriletisim.WSiletisimSoap.ReadDataTable
            Return MyBase.Channel.ReadDataTable(Sql, Tbl)
        End Function
        
        Public Function ReadDataTableXml(ByVal Sql As String, ByVal Tbl As String) As String Implements Sriletisim.WSiletisimSoap.ReadDataTableXml
            Return MyBase.Channel.ReadDataTableXml(Sql, Tbl)
        End Function
        
        Public Function ExecuteSql(ByVal Sql As String) As Boolean Implements Sriletisim.WSiletisimSoap.ExecuteSql
            Return MyBase.Channel.ExecuteSql(Sql)
        End Function
        
        Public Function UploadSatislar(ByVal Ds As System.Data.DataSet) As Boolean Implements Sriletisim.WSiletisimSoap.UploadSatislar
            Return MyBase.Channel.UploadSatislar(Ds)
        End Function
        
        Public Function UploadDataTable(ByVal Dt As System.Data.DataTable) As Boolean Implements Sriletisim.WSiletisimSoap.UploadDataTable
            Return MyBase.Channel.UploadDataTable(Dt)
        End Function
        
        Public Function YesNo(ByVal UserId As String, ByVal SendCode As String, ByVal Reply As Boolean) As String Implements Sriletisim.WSiletisimSoap.YesNo
            Return MyBase.Channel.YesNo(UserId, SendCode, Reply)
        End Function
    End Class
End Namespace
